---
start: 2024-07-03
end: 2024-07-05
published: 2024-12-23
year: '2024'
volume: '250'
booktitle: Proceedings of The 7nd International Conference on Medical Imaging with
  Deep Learning
shortname: MIDL
conference_number: '7'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MIDL-2024
month: 0
cycles: false
bibtex_editor: Burgos, Ninon and Petitjean, Caroline and Vakalopoulou, Maria and Christodoulidis,
  Stergios and Coupe, Pierrick and Delingette, Herv\'e and Lartizien, Carole and Mateus,
  Diana
editor:
- given: Ninon
  family: Burgos
- given: Caroline
  family: Petitjean
- given: Maria
  family: Vakalopoulou
- given: Stergios
  family: Christodoulidis
- given: Pierrick
  family: Coupe
- given: Hervé
  family: Delingette
- given: Carole
  family: Lartizien
- given: Diana
  family: Mateus
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 7nd International Conference on Medical Imaging with Deep Learning
    Held in Paris, France on 03-05 July 2024

  Published as Volume 250 by the Proceedings of Machine Learning Research on 23 December 2024.

  Volume Edited by:
    Ninon Burgos
    Caroline Petitjean
    Maria Vakalopoulou
    Stergios Christodoulidis
    Pierrick Coupe
    Hervé Delingette
    Carole Lartizien
    Diana Mateus

  Series Editors:
    Neil D. Lawrence
date_str: 03--05 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v250"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v250
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v250
email: ''
conference:
  name: Medical Imaging with Deep Learning
  url: https://2024.midl.io
  location: Paris, France
  dates:
  - *1
  - 2024-07-04
  - 2024-07-05
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: "/Users/neil/mlresearch/v250/MIDL2024.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v250/MIDL2024.bib
